#!/bin/bash

if [ $USER = "root"  ]
then

cat << EOF > /etc/apache2/sites-available/$1.test.conf 

<VirtualHost *:80>
        ServerName $1.test

        ServerAdmin juanfarias@localhost
        DocumentRoot /var/www/$1/public

        ErrorLog ${APACHE_LOG_DIR}/$1_error.log
        CustomLog ${APACHE_LOG_DIR}/$1_access.log combined
</VirtualHost>

EOF

ln -s /etc/apache2/sites-available/$1.test.conf /etc/apache2/sites-enabled/$1.test.conf

cat << EOF >> /etc/hosts
127.0.0.1       $1.test
EOF

systemctl restart apache2

else

echo "Precisa ser usúario root";

fi


